version: '3.8'

services:
  jenkins:
    build:
      context: .  # Ruta donde está el Dockerfile
      dockerfile: Dockerfile
    container_name: jenkins-server
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375  # Conexión Docker Desktop (Windows)
    ports:
      - "8080:8080"  # Puerto web de Jenkins
      - "50000:50000"  # Puerto para conectar agentes de Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistencia de datos de Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # Permitir acceso a Docker desde Jenkins
      - terraform_state:/terraform_state # Guardar el tfstate en un volumen persistente

    privileged: true  # Permitir permisos de Docker completos
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
