pipeline {
    agent any

    environment {
        TERRAFORM_PATH = '/usr/local/bin/terraform'  // Ruta de terraform en la máquina local
    }

    stages {
        stage('Run Terraform Init') {
            steps {
                script {
                    // Ejecuta terraform init en la máquina local
                    dir('Terraform') {
                    sh 'terraform init'  // El directorio de trabajo con los archivos .tf
                    }
                }
            }
        }
        stage('Run Terraform Plan') {
            steps {
                script {
                    // Ejecuta terraform plan en la máquina local
                    dir('Terraform') {
                    sh 'terraform plan'
                    }
                }
            }
        }
        stage('Run Terraform Apply') {
            steps {
                script {
                    // Ejecuta terraform apply en la máquina local
                    dir('Terraform') {
                    sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
    }

    post {
        always {
            // Aquí puedes agregar acciones de limpieza si es necesario
        }
    }
}
