pipeline {
    agent any

    stages {
        stage('Terraform Init') {
            steps {
                script {
                    sh 'terraform init'  // Esto ejecutará terraform en la máquina real
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    sh 'terraform plan'  // Ejecutar terraform plan
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    sh 'docker exec terraform-container terraform apply -auto-approve'  // Aplicar cambios
                }
            }
        }
    }
}
